/* Inserting the data into tables */
INSERT INTO CITIES (city,state) VALUES ('PUNE','MAHARASHTRA');
INSERT INTO CITIES (city,state) VALUES ('MUMBAI','MAHARASHTRA');

insert into warehouses (WNAME,LOCATION,EXTRA_CONTEXT,CITY_ID) VALUES ('LOCAL WAREHOUSE','PUNE',null,1);
insert into warehouses (WNAME,LOCATION,EXTRA_CONTEXT,CITY_ID) VALUES ('ADVANCE WAREHOUSE','PUNE',null,1);
insert into warehouses (WNAME,LOCATION,EXTRA_CONTEXT,CITY_ID) VALUES ('SUPERIOR WAREHOUSE','MUMBAI',null,2);

INSERT INTO STORES (WID,STORE_NAME,LOCATION_CITY) VALUES (1,'NEW KIRANA STORE','PUNE');
INSERT INTO STORES (WID,STORE_NAME,LOCATION_CITY) VALUES (1,'AAJ TAK STORE','PUNE');
INSERT INTO STORES (WID,STORE_NAME,LOCATION_CITY) VALUES (2,'SHANIVAARWADA STORE','PUNE');
INSERT INTO STORES (WID,STORE_NAME,LOCATION_CITY) VALUES (3,'GADA ELECTRONICS','MUMBAI');

INSERT INTO CUSTOMER (CNAME,ADDR,CU_CITY) VALUES ("MR. DIGVIJAY PATIL","NEW PUNE, OPPOSITE HOTEL","PUNE");
INSERT INTO CUSTOMER (CNAME,ADDR,CU_CITY) VALUES ("MR. ROHAN YADAV","OLD PUNE, OPPOSITE TO SCHOOLE","PUNE");

INSERT INTO ORDERS (CNO,ITEMNO,ODATE) VALUES (1,1,sysdate());
INSERT INTO ORDERS (CNO,ITEMNO,ODATE) VALUES (1,2,sysdate());
INSERT INTO ORDERS (CNO,ITEMNO,ODATE) VALUES (2,1,sysdate());
INSERT INTO ORDERS (CNO,ITEMNO,ODATE) VALUES (2,1,sysdate());

INSERT INTO ITEMS (DESCRIPTION,WEIGHT,COST) values ("IPHONE 14 PRO MAX",0.3,96);
INSERT INTO ITEMS (DESCRIPTION,WEIGHT,COST) values ("SAMSUNG SMART PHONE",0.45,10);


select min(Weight) from Items;
/*
# min(Weight)
'0.30'
*/

SELECT * FROM WAREHOUSES WHERE CITY_ID = 1;
/*
# WID, WNAME, LOCATION, EXTRA_CONTEXT, CITY_ID
'1', 'LOCAL WAREHOUSE', 'PUNE', NULL, '1'
'2', 'ADVANCE WAREHOUSE', 'PUNE', NULL, '1'
*/

SELECT ORDERS.ODATE,ITEMS.DESCRIPTION,ITEMS.COST,CUSTOMER.CNAME,CUSTOMER.ADDR FROM ORDERS 
INNER JOIN ITEMS ON ITEMS.ITEMNO = ORDERS.ITEMNO
INNER JOIN CUSTOMER ON CUSTOMER.CNO = ORDERS.CNO
WHERE CUSTOMER.CNO = 1;
/*
# ODATE, DESCRIPTION, COST, CNAME, ADDR
'2023-05-24', 'IPHONE 14 PRO MAX', '96.00', 'MR. DIGVIJAY PATIL', 'NEW PUNE, OPPOSITE HOTEL'
'2023-05-24', 'SAMSUNG SMART PHONE', '10.00', 'MR. DIGVIJAY PATIL', 'NEW PUNE, OPPOSITE HOTEL'
*/

SELECT WAREHOUSES.WNAME,COUNT(1) noOfStores FROM STORES
inner join WAREHOUSES on WAREHOUSES.wid = stores.wid
GROUP BY  WAREHOUSES.WNAME
HAVING COUNT(1) > 0
ORDER BY noOfStores desc limit 1;
/*
# WNAME, noOfStores
'LOCAL WAREHOUSE', '2'
*/

SELECT orders.ITEMNO, items.DESCRIPTION, COUNT(1) AS order_count
FROM orders
inner join items on orders.ITEMNO = items.ITEMNO
GROUP BY orders.ITEMNO,items.DESCRIPTION
HAVING order_count = (SELECT MIN(order_count) FROM (SELECT ITEMNO, COUNT(1) AS order_count FROM orders GROUP BY ITEMNO) AS counts);
/*
# ITEMNO, DESCRIPTION, order_count
'2', 'SAMSUNG SMART PHONE', '1'
*/


select Customer.CNO,customer.CNAME,CUSTOMER.ADDR,CUSTOMER.CU_CITY,ORDERS.ODATE,ITEMS.DESCRIPTION,ITEMS.WEIGHT,ITEMS.COST
FROM CUSTOMER
INNER JOIN ORDERS ON ORDERS.CNO = CUSTOMER.CNO
INNER JOIN ITEMS ON ITEMS.ITEMNO = ORDERS.ITEMNO;
/*
# CNO, CNAME, ADDR, CU_CITY, ODATE, DESCRIPTION, WEIGHT, COST
'1', 'MR. DIGVIJAY PATIL', 'NEW PUNE, OPPOSITE HOTEL', 'PUNE', '2023-05-24', 'IPHONE 14 PRO MAX', '0.30', '96.00'
'1', 'MR. DIGVIJAY PATIL', 'NEW PUNE, OPPOSITE HOTEL', 'PUNE', '2023-05-24', 'SAMSUNG SMART PHONE', '0.45', '10.00'
'2', 'MR. ROHAN YADAV', 'OLD PUNE, OPPOSITE TO SCHOOLE', 'PUNE', '2023-05-24', 'IPHONE 14 PRO MAX', '0.30', '96.00'
'2', 'MR. ROHAN YADAV', 'OLD PUNE, OPPOSITE TO SCHOOLE', 'PUNE', '2023-05-24', 'IPHONE 14 PRO MAX', '0.30', '96.00'
*/

SELECT * FROM CITIES;
/*
# CITY_ID, CITY, STATE
'1', 'PUNE', 'MAHARASHTRA'
'2', 'MUMBAI', 'MAHARASHTRA'
*/

SELECT * FROM CUSTOMER;
/*
# CNO, CNAME, ADDR, CU_CITY
'1', 'MR. DIGVIJAY PATIL', 'NEW PUNE, OPPOSITE HOTEL', 'PUNE'
'2', 'MR. ROHAN YADAV', 'OLD PUNE, OPPOSITE TO SCHOOLE', 'PUNE'
*/

SELECT * FROM ITEMS;
/*
1, IPHONE 14 PRO MAX, 0.30, 96.00
2, SAMSUNG SMART PHONE, 0.45, 10.00
*/

SELECT * FROM ORDERS;
/*
1, 2023-05-24, 1, 1
2, 2023-05-24, 1, 2
3, 2023-05-24, 2, 1
4, 2023-05-24, 2, 1
*/

SELECT * FROM STORES;
/*
1, NEW KIRANA STORE, PUNE, 1
2, AAJ TAK STORE, PUNE, 1
3, SHANIVAARWADA STORE, PUNE, 2
4, GADA ELECTRONICS, MUMBAI, 3
*/

SELECT * FROM WAREHOUSES;
/*
1, LOCAL WAREHOUSE, PUNE, , 1
2, ADVANCE WAREHOUSE, PUNE, , 1
3, SUPERIOR WAREHOUSE, MUMBAI, , 2
*/
